### ISSUE TITLE
Secret WordPress core feature: subdirectory

### ISSUE THREAD

**Issue by szepeviktor** [timber/learn-timber-theme#1]
If one is having a lot of development files in the root, or just to tidy up things: [core finds theme files in a subdirectory](https://github.com/WordPress/WordPress/blob/89e99f57a2a175ccb75282d1a7eefb0bfce94bcb/wp-includes/theme.php#L515)!

I propose `/template`

**Comment by szepeviktor** [comment]
E.g. the starter theme has:

- .gitignore
- .travis.yml
- LICENSE
- README.md
- composer.json
- humans.txt
- phpunit.xml

**Comment by gchtr** [comment]
@szepeviktor I never looked at that function in detail. But what do you mean exactly? What files or folders should we move where? 🙂

**Comment by szepeviktor** [comment]
- theme files will have their own subdirectory
- development files (mainly configs) will remain in the root
- non-theme files may also have their own subdir, e.g. `src/` for PHP classes

**Comment by gchtr** [comment]
What I think the function you linked means is that you could move the whole theme into a subfolder. So instead of

```
wp-content/themes/getting-started-theme
```

you could have

```
wp-content/themes/subfolder/getting-started-theme
```

But it’s not possible to move template files like **index.php** and **single.php** from the theme root folder to a subfolder just like that. WordPress needs at least an **index.php** as entry point for templates files. And I think we mostly follow the WordPress default here, see the [Template Files](https://developer.wordpress.org/themes/basics/template-files/) section in the Theme Developer Handbook. It seems to me as if most WordPress themes work like that and developers are used to it.

But I totally agree that it’s not very clean to mix template files with other config and development files 👍.

**Comment by szepeviktor** [comment]
> `wp-content/themes/subfolder/getting-started-theme`

_Nooooooooooooooooooooooooooooooooooooooooo!_ :)

WP files: `wp-content/themes/getting-started-theme/template/index.php`

other files: `wp-content/themes/getting-started-theme/composer.json`

**Comment by gchtr** [comment]
> WP files: `wp-content/themes/getting-started-theme/template/index.php`

I checked this, it doesn’t work 😉. At least not by default.

**Comment by szepeviktor** [comment]
It works.
Please see https://github.com/WordPress/WordPress/blob/89e99f57a2a175ccb75282d1a7eefb0bfce94bcb/wp-includes/theme.php#L515

But if you have the theme active you must switch to another one and switch back.

**Comment by szepeviktor** [comment]
and of course `require_once dirname(__DIR__) . '/vendor/autoload.php';` in functions.php

**Comment by gchtr** [comment]
> Please see [WordPress/WordPress:wp-includes/theme.php@`89e99f5`#L515](https://github.com/WordPress/WordPress/blob/89e99f57a2a175ccb75282d1a7eefb0bfce94bcb/wp-includes/theme.php#L515)

That’s exactly what I mean! This function figures out **which themes are available**, but **not which template files**. I can put themes in subdirectories, but apparently not template files.

> But if you have the theme active you must switch to another one and switch back.

If I move the **index.php** file to `wp-content/themes/getting-started-theme/template/index.php`, then the theme isn’t even listed in the WordPress’s theme settings and I can’t switch back to it. That’s because each theme needs an **index.php** to work.

The logic that figures out which template to load is in [**wp-includes/template-loader.php**](https://github.com/WordPress/WordPress/blob/26bda18a23174afb048afbe62296c76a62add542/wp-includes/template-loader.php). And the function that actually figures out which file to load is [`locate_template()`](https://github.com/WordPress/WordPress/blob/26bda18a23174afb048afbe62296c76a62add542/wp-includes/template.php#L653), and it is not looking into subdirectories.

I don’t know how you do it, but I really can’t get this to work, even with

```
require_once __DIR__ . '/vendor/autoload.php';
```

😊

**Comment by szepeviktor** [comment]
Okay!
I send a PR...

**Comment by gchtr** [comment]
Oh, of course! You put **all WordPress related files** in the **template** folder, including **style.css** and **functions.php** 💡. Now I get it!

I’ll keep the discussion in here and not answer in the pull request.

> We should figure out what to do with `views`!
> 
>     1. keep it in the root
> 
>     2. move it to `template/`

The **views** folder should still work if you’d put them in **template**, because of the load order in Timber, which is defined [in this Guide](https://timber.github.io/docs/getting-started/theming/#render). There might be side effects for other files and functions we didn’t think about yet and which might not even surface, even if we try to test it thoroughly.

Suppose if you have asset files, you could have them in the theme root folder and build them to the **template/build** or **template/dist** folder. Or put them in **template** as well.

I’d rather use the name **theme** instead of **template**, because in WordPress, templates are mostly template files for the [Template Hierarchy](https://wphierarchy.com/).

I kinda like the idea 👍. However, I still feel like it might be confusing for developers, if we use a structure like this. For a low-entry level theme that shows how to transition from a WordPress theme to a Timber theme, I think we shouldn’t do it. But we could maybe do it for the [Starter Theme](https://github.com/timber/starter-theme). Or we could document this in a new Guide.

I wonder what @jarednova thinks about this.

**Comment by szepeviktor** [comment]
> low-entry level theme

I cannot argue with this _low_ thing :)
One **must** be irritated by the mixture of files with very different purposes in 1 directory.

> Suppose if you have asset files, you could have them in the theme root folder and build them to the template/build or template/dist folder. Or put them in template as well.

Yes this subdir opens a wide spectrum of possibilities!

**Comment by gchtr** [comment]
> One **must** be irritated by the mixture of files with very different purposes in 1 directory.

You’re right. I can’t say anything against that either 🤷‍♂️😄

**Comment by jarednova** [comment]
Just catching up on this. I agree that it's something to look into, but in [the starter theme](https://github.com/timber/starter-theme) and not the "getting started theme." Now that we have two, I think this will make it easier to separate their goals.

- `timber/getting-started-theme` (this repo) is meant to link up to the Getting Started section in the docs. It should be as minimal as possible to introduce the main Timber concepts in a way that's recognizable to people w some WordPress knowledge. 

- `timber/starter-theme` to showcases the current best practices in building a site with Timber. It should remain current with the features of the most recent version and provide a strong example which to base theme development work from.

Based on this I think there are two action items:

1. Clarify the name. Since the "getting-started-theme" is the new kid on the block, I think we should find a more differentiated name: `setup-theme`? `basic-theme`? `base-theme`? for this repo
2. Let's move PR #3 into `starter-theme`; this will also give us a chance to totally rectify `templates` vs. `views` for Twig files. In that PR we can debate and come to an agreed-upon names for all the appropriate directories

**Comment by szepeviktor** [comment]
Okay.

> In that PR we can debate and come to an agreed-upon names for all the appropriate directories

I've totally forgot about that 22 day old PR!

**Comment by gchtr** [comment]
>     1. Clarify the name. Since the "getting-started-theme" is the new kid on the block, I think we should find a more differentiated name: `setup-theme`? `basic-theme`? `base-theme`? for this repo

I see. The term "start" might be confused with Starter Theme. But if we’d call it something like "base", then I would assume there’d also be a base with Timber code. But actually, we start with WordPress code, like here:

https://github.com/timber/getting-started-theme/blob/135e3362725049fcb250b636dd0e68229e5a53ae/single.php#L1

Maybe we could use one of the following names:

- `tutorial-theme`
- `introduction-theme`

What do you think?

**Comment by szepeviktor** [comment]
To me `tutorial-theme` is very similar to `getting-started-theme`.

How about `learn-timber-theme` ?

**Comment by jarednova** [comment]
@szepeviktor I think Learn Timber is 👍. Speaks to the purpose (and also helps to make me think of some good places to take it next). 

@gchtr you got the ball rolling here so wanted to make sure you were on the same page before proceeding

**Comment by gchtr** [comment]
@szepeviktor @jarednova I like «Learn Timber Theme» / `learn-timber-theme` 👍.

I’ll make sure to update the name in all places.

**Comment by szepeviktor** [comment]
Let's go!

**Comment by szepeviktor** [comment]
Done.

https://github.com/timber/learn-timber-theme/blob/master/composer.json#L2
